name: Build - Win

permissions:
  contents: write

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-windows:
    name: Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: x64
            node_arch: x64
            msvc_arch: x64
            vcpkg_triplet: x64-windows-static
            node_version: 18
          - arch: x86
            node_arch: x86
            msvc_arch: x86
            vcpkg_triplet: x86-windows-static
            node_version: 18
          - arch: arm64
            node_arch: arm64
            msvc_arch: amd64_arm64
            vcpkg_triplet: arm64-windows-static
            node_version: 18

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Setup vcpkg
        run: |
          C:\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install OpenSSL
        run: |
          C:\vcpkg\vcpkg install openssl:${{ matrix.vcpkg_triplet }}
        shell: cmd

      - name: NPM Install
        run: |
          npm install --ignore-scripts
        shell: cmd

      - name: Configure
        run: |
          npx cmake-js configure --CDCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake" --CDVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}
        shell: cmd
        env:
          npm_config_build_from_source: 'true'

      - name: Build
        run: |
          npx cmake-js build
        shell: cmd
        env:
          npm_config_build_from_source: 'true'

      - name: Copy prebuild
        run: >
          npx pkg-prebuilds-copy
          --baseDir build/Release
          --source node_datachannel.node
          --name=node_datachannel
          --strip
          --napi_version=8
          --arch=${{ matrix.arch }}
        shell: cmd

      - name: Upload prebuilds
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-win-${{ matrix.arch }}
          path: prebuilds
          retention-days: 7
